-- =====================================================
-- Script SQL — Tabla PEDIDO
-- LibreríaOnline — Oracle Cloud (ADMIN schema)
-- =====================================================

CREATE TABLE ADMIN.PEDIDO (
    ID               NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ID_USUARIO       NUMBER        NOT NULL,
    ID_PRODUCTO      NUMBER        NOT NULL,
    NOMBRE_PRODUCTO  VARCHAR2(200),
    CANTIDAD         NUMBER        NOT NULL,
    PRECIO_UNITARIO  NUMBER(10,2)  NOT NULL,
    TOTAL            NUMBER(10,2),
    ESTADO           VARCHAR2(20)  DEFAULT 'PENDIENTE',
    FECHA_PEDIDO     TIMESTAMP     DEFAULT CURRENT_TIMESTAMP,
    DIRECCION_ENVIO  VARCHAR2(300)
);

-- Datos de prueba
INSERT INTO ADMIN.PEDIDO (ID_USUARIO, ID_PRODUCTO, NOMBRE_PRODUCTO, CANTIDAD, PRECIO_UNITARIO, TOTAL, ESTADO, DIRECCION_ENVIO)
VALUES (2, 1, 'Cien años de soledad', 1, 12990, 12990, 'PENDIENTE', 'Av. Providencia 123, Santiago');

INSERT INTO ADMIN.PEDIDO (ID_USUARIO, ID_PRODUCTO, NOMBRE_PRODUCTO, CANTIDAD, PRECIO_UNITARIO, TOTAL, ESTADO, DIRECCION_ENVIO)
VALUES (2, 3, 'Matemáticas 3° Medio', 2, 15990, 31980, 'CONFIRMADO', 'Calle Las Flores 456, Providencia');

INSERT INTO ADMIN.PEDIDO (ID_USUARIO, ID_PRODUCTO, NOMBRE_PRODUCTO, CANTIDAD, PRECIO_UNITARIO, TOTAL, ESTADO, DIRECCION_ENVIO)
VALUES (3, 2, 'El Principito', 1, 8990, 8990, 'ENTREGADO', 'Pasaje El Monte 789, Ñuñoa');

COMMIT;
